onboarding = false

[keys]
prefix = "backtick"
split_vertical = "ctrl+t"
split_horizontal = "ctrl+y"
close_pane = "ctrl+x"

[ui]
mouse_capture = true
copy_on_select = true
mouse_scroll_lines = 5
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "system"

[terminal]
new_cwd = "follow"

[theme]
name = "gruvbox"
auto_switch = false

[remote]
manage_ssh_config = true

[experimental]
switch_ascii_input_source_in_prefix = false
pane_history = false
